### ISSUE TITLE
Can't compile with your fork of Audio lib due to missing methods in Resampler

### ISSUE THREAD

**Issue by t0mg** [alex6679/teensy-4-async-inputs#1]
Hi, I'm trying to build on platformIO to get [your example](https://github.com/alex6679/ESP32_I2S_Teensy4) to work, which led me to this repo maybe a year ago (full story for context [here](https://threadreaderapp.com/thread/1465465658519572480.html) and [here](https://bsky.app/profile/did:plc:jq4tmkkiuajes2h55cwev324/post/3knrm4yvazf2w). I had it working for a while, but unrelated issues made me wipe the pio libs and now I can't compile anymore. It seems like there are missing declarations in https://github.com/alex6679/Audio/blob/master/Resampler.h (fixIncrement, setPos, updateIncrement) among other mismatches between the cpp and h files in your fork.

Are these up to date? Or is there a more recent way to get ESP32 I2S input into a T4 ?

Thanks!

**Comment by alex6679** [comment]
Hi, sorry for that. I reverted the last changes I made to async_input.h. Now you should be able to use Paul's original Audio library again. It's quite some time since I pulled from the audio library main branch and my fork is currently not up-to-date. So it's better to use the original audio library.
Hope that solves your problem.

**Comment by t0mg** [comment]
Indeed it compiles again now! Thanks a lot for the quick response :)

I did have to remove the example1 folder for the project to build though (if I remember correctly I am using the example I found in https://github.com/JayShoe/esp32_T4_bt_music_receiver/blob/main/Teensy4/output_i2s2_16bit.cpp)
